### ISSUE TITLE
Deep dive on "paz"- a platform for Continuous Deployment built on CoreOS and Docker

### ISSUE THREAD

**Issue by lukebond** [CoreOS-London/speak#3]
At container.camp, London's first Docker-focused conference, I presented a platform I've been building called "paz"- a Docker-based platform for deploying and hosting Docker containers, running on CoreOS. In that talk I focused on what "paz" is and why developers might want to use it.

In this talk I'll take a technical deep dive into the nuts and bolts of how Paz works, covering its use of CoreOS, Fleet, Etcd, HAProxy and Confd.

**Comment by fintanr** [comment]
Speaking March 10th.
