### ISSUE TITLE
CoreOS and Project Calico

### ISSUE THREAD

**Issue by neiljerram** [CoreOS-London/speak#5]
Hi there!  Project Calico (www.projectcalico.org) is an approach for networking virtualized workloads such as containers or VMs.  At the next CoreOS meetup, I'd love to talk more about that, and present a demo, if that would be welcome.  Please do let me know what you think.

Some refs:
- http://www.projectcalico.org/
- https://github.com/Metaswitch/calico-docker-prototype
- https://github.com/Metaswitch/calico

**Comment by fintanr** [comment]
Hi,

We have a new venue confirmed and would love to have you guys along - the next meetup is planned for March 10th if that suits?

- Fintan

**Comment by neiljerram** [comment]
Hi Fintan,

Sorry for the delay in responding.  Yes, we love to come on March 10th and to present if possible - do you still have a slot open?

Thanks - Neil

**Comment by fintanr** [comment]
Hi Neil,

We would love to have you come speak - please drop me an e-mail (fintanr at gmail ) and we can sort out the details.

- Fintan

**Comment by fintanr** [comment]
Talking on March 10th.
